apiVersion: apps/v1
kind: Deployment
metadata: { }
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ""
  template:
    metadata:
      labels:
        app: ""
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
